App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'


urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('cart/', views.cart_view, name = "cart"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),

]

App_Shop/urls.py
from django.urls import path
from App_Shop import views


app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),

]

contact/urls.py
from django.urls import path
# from contact.views import contact_view
from .views import contact_view, search_view

urlpatterns = [
    path('', contact_view, name='contact'),
    path('search/', search_view, name='search'),
]

eexpress/urls.py
from django.contrib import admin
from django.urls import path, include


# To show media files

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
    path('contact/', include('contact.urls')),
    # path('accounts/',include('allauth.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Shop/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length = 20)
    created = models.DateTimeField(auto_now_add = True)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"


#model for Product
class Product(models.Model):
    mainimage = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=264)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,related_name="category")
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=3000, verbose_name='Description')
    price =models.FloatField()
    old_price = models.FloatField(default=0.00, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return self.name


    class Meta:
        ordering = ['-created',]

App_Shop/views.py
from django.shortcuts import render


#import views
from django.views.generic import ListView, DetailView

#models
from App_Shop.models import Product, Category

#Mixin
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

class Home(ListView):
    model = Product
    Categories = Category.objects.all()
    print(Categories)
    template_name = 'App_Shop/home.html'
    # return value of get_context_data is passed to template
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = self.Categories
        return context

class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'App_Shop/product_detail.html'

templates/App_Shop/home.html
{% extends 'base.html' %}

{% block body_block %}
{% include 'Slider.html' %}
{% include 'featured.html' %}


<div class="container flex">
  <h2 class="my">Featured Products</h2>
  <div class="row">
    {% for product in object_list %}
    <div class="col-md-6 col-sm-12 col-lg-3">
      <div class="card product-item border-0 mb-4">
        <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
          <img class="img-fluid w-100" src="/media/{{product.mainimage}}" alt="">
        </div>
        <div class=" card-body border-left border-right text-center p-0 pt-4 pb-3">
          <h6 class="text-truncate mb-3"><a
              href="{% url 'App_Shop:product_detail' pk=product.pk %}">{{product.name}}</a></h6>
          <div class="d-flex justify-content-center">
            <h6>{{product.price|floatformat:2}}</h6>
            <h6 class="text-muted ml-2"><del>{{product.old_price|floatformat:2}}</del></h6>
          </div>
        </div>
        <div class="card-footer d-flex justify-content-between bg-light border">
          <a href="{% url 'App_Shop:product_detail' pk=product.pk %}" class="btn btn-sm text-dark p-0"><i
              class="fas fa-eye text-primary mr-1"></i>View Detail</a>
          <a href="{% url 'App_Shop:product_detail' pk=product.pk %}" class="btn btn-sm text-dark p-0"><i
              class="fas fa-shopping-cart text-primary mr-1"></i>Add To
            Cart</a>
        </div>
      </div>
      <!-- <figure class="card card-product">
        <div class="img-wrap">
          <img src="/media/{{product.mainimage}}" style="width:100%; height:300px;">
        </div>
        <figcaption class="info-wrap">
          <h6 class="title"> <a href="{% url 'App_Shop:product_detail' pk=product.pk %}">{{product.name}}</a></h6>
          <div class="action-wrap">
            <div class="price-wrap h5">
              <span class="price-new">&#2547; {{product.price|floatformat:2}}</span>
              <span class="price-old"> <strike>&#2547; {{product.old_price|floatformat:2}}</strike></span>
            </div>
          </div>
        </figcaption>
      </figure> -->
    </div>
    {% endfor %}
  </div>

  <div class="container-fluid offer pt-5">
    <!--<div class="row px-xl-5">-->
    <!--  <div class="col-md-6 pb-4">-->
    <!--    <div class="position-relative bg-secondary text-center text-md-right text-white mb-2 py-5 px-5">-->
    <!--      <img src="img/offer-1.png" alt="">-->
    <!--      <div class="position-relative" style="z-index: 1;">-->
    <!--        <h5 class="text-uppercase text-primary mb-3">20% off the all order</h5>-->
    <!--        <h1 class="mb-4 font-weight-semi-bold">Spring Collection</h1>-->
    <!--        <a href="" class="btn btn-outline-primary py-md-2 px-md-3">Shop Now</a>-->
    <!--      </div>-->
    <!--    </div>-->
    <!--  </div>-->
    <!--  <div class="col-md-6 pb-4">-->
    <!--    <div class="position-relative bg-secondary text-center text-md-left text-white mb-2 py-5 px-5">-->
    <!--      <img src="img/offer-2.png" alt="">-->
    <!--      <div class="position-relative" style="z-index: 1;">-->
    <!--        <h5 class="text-uppercase text-primary mb-3">20% off the all order</h5>-->
    <!--        <h1 class="mb-4 font-weight-semi-bold">Winter Collection</h1>-->
    <!--        <a href="" class="btn btn-outline-primary py-md-2 px-md-3">Shop Now</a>-->
    <!--      </div>-->
    <!--    </div>-->
    <!--  </div>-->
    <!--</div>-->
  </div>
</div>

{% endblock %}

templates/App_Shop/product_detail.html
{% extends 'base.html' %}
{% block body_block %}

<style>
  
</style>
<div class="container ">
  <div class="container-fluid py-5">
        <div class="row px-xl-5">
            <div class="col-lg-5 pb-5">
                <div id="product-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner border">
                        <div class="carousel-item active">
                            <img class="w-100 h-100" src="/media/{{object.mainimage}}" alt="Image">
                        </div>
                        <div class="carousel-item">
                            <img class="w-100 h-100" src="/media/{{object.mainimage}}" alt="Image">
                        </div>
                        <div class="carousel-item">
                            <img class="w-100 h-100" src="/media/{{object.mainimage}}" alt="Image">
                        </div>
                       
                    <a class="carousel-control-prev" href="#product-carousel" data-slide="prev">
                        <i class="fa fa-2x fa-angle-left text-dark"></i>
                    </a>
                    <a class="carousel-control-next" href="#product-carousel" data-slide="next">
                        <i class="fa fa-2x fa-angle-right text-dark"></i>
                    </a>
                </div>
            </div>

            <div class="col-lg-7 pb-5">
                <h3 class="font-weight-semi-bold">{{object.name}}</h3>
                <!-- <div class="d-flex mb-3">
                    <div class="text-primary mr-2">
                        <small class="fas fa-star"></small>
                        <small class="fas fa-star"></small>
                        <small class="fas fa-star"></small>
                        <small class="fas fa-star-half-alt"></small>
                        <small class="far fa-star"></small>
                    </div>
                    <small class="pt-1">(50 Reviews)</small>
                </div> -->
                <h3 class="font-weight-semi-bold mb-4">{{object.price}} TK</h3>
                
                <!-- <div class="d-flex mb-3">
                    <p class="text-dark font-weight-medium mb-0 mr-3">Sizes:</p>
                    <form>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="size-1" name="size">
                            <label class="custom-control-label" for="size-1">XS</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="size-2" name="size">
                            <label class="custom-control-label" for="size-2">S</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="size-3" name="size">
                            <label class="custom-control-label" for="size-3">M</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="size-4" name="size">
                            <label class="custom-control-label" for="size-4">L</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="size-5" name="size">
                            <label class="custom-control-label" for="size-5">XL</label>
                        </div>
                    </form>
                </div> -->
                <!-- <div class="d-flex mb-4">
                    <p class="text-dark font-weight-medium mb-0 mr-3">Colors:</p>
                    <form>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="color-1" name="color">
                            <label class="custom-control-label" for="color-1">Black</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="color-2" name="color">
                            <label class="custom-control-label" for="color-2">White</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="color-3" name="color">
                            <label class="custom-control-label" for="color-3">Red</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="color-4" name="color">
                            <label class="custom-control-label" for="color-4">Blue</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="color-5" name="color">
                            <label class="custom-control-label" for="color-5">Green</label>
                        </div>
                    </form>
                </div> -->
                <div class="d-flex align-items-center mb-4 pt-2">
              
                    <a  href="{% url 'App_Order:add' pk=object.pk %}">
                      <button class="btn btn-primary px-3"><i class="fa fa-shopping-cart mr-1"></i> Add To Cart</button>

                    </a>
                </div>
                <div class="d-flex pt-2">
                    <p class="text-dark font-weight-medium mb-0 mr-2">Share on:</p>
                    <div class="d-inline-flex">
                        <a class="text-dark px-2" href="">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a class="text-dark px-2" href="">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a class="text-dark px-2" href="">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                        <a class="text-dark px-2" href="">
                            <i class="fab fa-pinterest"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="container">
              <p >{{object.detail_text|linebreaks}}</p>

            </div>
        </div>
 

</div>
{% endblock %}