App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [

    path('signup/', views.sign_up, name = 'signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),

]

App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'


urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('cart/', views.cart_view, name = "cart"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),

]

App_Payment/urls.py
from django.urls import path
from App_Payment import views
app_name = "App_Payment"

urlpatterns = [
    path('checkout/', views.checkout, name="checkout"),
    path('pay/', views.payment, name="payment"),
    #path('status/', views.complete, name="complete"),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name="purchase"),
    path('orders/', views.order_view, name="orders"),

]

App_Shop/urls.py
from django.urls import path
from App_Shop import views


app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),

]

contact/urls.py
from django.urls import path
# from contact.views import contact_view
from .views import contact_view, search_view

urlpatterns = [
    path('', contact_view, name='contact'),
    path('search/', search_view, name='search'),
]

eexpress/urls.py
from django.contrib import admin
from django.urls import path, include


# To show media files

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
    path('contact/', include('contact.urls')),
    # path('accounts/',include('allauth.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Slider.html
<!-- Navbar Start -->
<div class="container-fluid mb-5">
    <div class="row border-top px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100"
                data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                <h6 class="m-0">Product Categories</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <nav class="collapse show navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0"
                id="navbar-vertical">
                <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link" data-toggle="dropdown">Soap's <i
                                class="fa fa-angle-down float-right mt-1"></i></a>
                        <div class="dropdown-menu position-absolute bg-secondary border-0 rounded-0 w-100 m-0">
                            <a href="" class="dropdown-item">Organic Soap</a>
                            <a href="" class="dropdown-item">Non-Organic Soap</a>

                        </div>
                    </div>

                </div>
            </nav>
        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span
                            class="text-primary font-weight-bold border px-3 mr-1">F</span>Fermado</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <!--<div class="navbar-nav mr-auto py-0">-->
                    <!--    <a href="index.html" class="nav-item nav-link active">Home</a>-->
                    <!--    <a href="shop.html" class="nav-item nav-link">Shop</a>-->
                    <!--    <a href="detail.html" class="nav-item nav-link">Shop Detail</a>-->
                    <!--    <div class="nav-item dropdown">-->
                    <!--        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages</a>-->
                    <!--        <div class="dropdown-menu rounded-0 m-0">-->
                    <!--            <a href="cart.html" class="dropdown-item">Shopping Cart</a>-->
                    <!--            <a href="checkout.html" class="dropdown-item">Checkout</a>-->
                    <!--        </div>-->
                    <!--    </div>-->
                        <!-- <a href="con" class="nav-item nav-link">Contact</a> -->
                    <!--    <a href="{% url 'contact' %}" class="nav-item nav-link">Contact</a>-->
                    <!--</div>-->

                </div>
            </nav>

            <div id="header-carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active" style="height: 410px;">
                        <img class="img-fluid" src="https://i.ibb.co/BqcMtss/pexels-amy-t-1661905.jpg" alt="Image">
                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                            <div class="p-3" style="max-width: 700px;">
                                <h4 class="text-light text-uppercase font-weight-medium mb-3">20% Off Your First Order
                                </h4>
                                <h3 class="display-4 text-white font-weight-semi-bold mb-4">ensure 100% organic and quality products</h3>
                                <a href="" class="btn btn-light py-2 px-3">Shop Now</a>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item" style="height: 410px;">
                        <img class="img-fluid" src="https://i.ibb.co/GtVycGC/pexels-karolina-grabowska-5632334.jpg" alt="Image">
                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                            <div class="p-3" style="max-width: 700px;">
                                <h4 class="text-light text-uppercase font-weight-medium mb-3">10% Off Your First Order
                                </h4>
                                <h3 class="display-4 text-white font-weight-semi-bold mb-4">Reasonable Price</h3>
                                <a href="" class="btn btn-light py-2 px-3">Shop Now</a>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
                    <div class="btn btn-dark" style="width: 45px; height: 45px;">
                        <span class="carousel-control-prev-icon mb-n2"></span>
                    </div>
                </a>
                <a class="carousel-control-next" href="#header-carousel" data-slide="next">
                    <div class="btn btn-dark" style="width: 45px; height: 45px;">
                        <span class="carousel-control-next-icon mb-n2"></span>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
<!-- Navbar End -->

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
    rel="stylesheet">

  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

  <!-- Libraries Stylesheet -->
  <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <title>{% block title_block %} Fermado {% endblock %}</title>
  <style>
    .card {
      height: 350px;
    }

    .card-product:after {
      content: "";
      display: table;
      clear: both;
      visibility: hidden;

    }

    .card-product .price_new,
    .card-product .price {
      margin-right: 5px;
    }

    .card-product .price-old {
      color: #999;
    }

    .card-product .img-wrap {
      border-radius: 3px 3px 0 0;
      overflow: hidden;
      position: relative;
      height: 220px;
      text-align: center;
    }

    .card-product .img-wrap img {
      max-height: 100%;
      max-width: 100%;
      object-fit: cover;
    }


    .card-product .info-wrap {
      overflow: hidden;
      padding: 15px;
      border-top: 1px solid #eee;
    }

    .card-product .action-wrap {
      padding-top: 4px;
      margin-top: 4px;
    }

    .card-product .bottom-wrap {
      padding: 15px;
      border-top: 1px solid #eee;

    }

    .card-Product .title {
      margin-top: 0px;
    }

    .whatsapp-chat{
        position: fixed;
        bottom: 05% !important;
        right:05% !important;
    }
  </style>


<a href="https://api.whatsapp.com/send/?phone=%2B8801742011181&text=I'm%20interested%20to%20buy%20this%20product" class='whatsapp-chat'>
  <img src="https://i.ibb.co/cLqGNqy/pngtree-whatsapp-mobile-software-icon-png-image-6315991.png" alt="whatsapp" width="60px" />

</a>
<!--<script>-->
<!--  "use strict";-->

<!--  !function() {-->
<!--    var t = window.driftt = window.drift = window.driftt || [];-->
<!--    if (!t.init) {-->
<!--      if (t.invoked) return void (window.console && console.error && console.error("Drift snippet included twice."));-->
<!--      t.invoked = !0, t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ],-->
<!--      t.factory = function(e) {-->
<!--        return function() {-->
<!--          var n = Array.prototype.slice.call(arguments);-->
<!--          return n.unshift(e), t.push(n), t;-->
<!--        };-->
<!--      }, t.methods.forEach(function(e) {-->
<!--        t[e] = t.factory(e);-->
<!--      }), t.load = function(t) {-->
<!--        var e = 3e5, n = Math.ceil(new Date() / e) * e, o = document.createElement("script");-->
<!--        o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + n + "/" + t + ".js";-->
<!--        var i = document.getElementsByTagName("script")[0];-->
<!--        i.parentNode.insertBefore(o, i);-->
<!--      };-->
<!--    }-->
<!--  }();-->
<!--  drift.SNIPPET_VERSION = '0.3.1';-->
<!--  drift.load('95sk2szmx4nt');-->
<!--  </script>-->


</head>

<body>

  {% include 'topbar.html' %}
  {% include 'navbar.html' %}

  <div class="container-flex">
    <div class="messages container mt-2">
      {% if messages %}
      {% for messages in messages %}
      <div {% if messages.tags %} class="alert alert-{{messages.tags}}{% endif %}" role="alert">
        {{messages}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span
            aria-hidden="true">&times;</span> </button>
      </div>
      {% endfor %}
      {% endif %}
    </div>
    <div class="container-flex">
      {% block body_block %} {% endblock %}
    </div>
    {% include 'footer.html' %}

  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>


  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

</body>

</html>

templates/featured.html
<!-- Featured Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5 pb-3">
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                <h1 class="fa fa-check text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">Quality Product</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                <h1 class="fa fa-shipping-fast text-primary m-0 mr-2"></h1>
                <h5 class="font-weight-semi-bold m-0">Fast Delivery</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                <h1 class="fas fa-exchange-alt text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">14-Day Return</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                <h1 class="fa fa-phone-volume text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">24/7 Support</h5>
            </div>
        </div>
    </div>
</div>
<!-- Featured End -->

templates/footer.html
<!-- Footer Start -->


<!-- Subscribe Start -->



<!-- Subscribe End -->

<div class="container-fluid bg-secondary text-dark mt-5 pt-5">


    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <a href="" class="text-decoration-none">
                <h1 class="mb-4 display-5 font-weight-semi-bold"><span
                        class="text-primary font-weight-bold border border-white px-3 mr-1">F</span>Fermado</h1>
            </a>
            <p>Spa, Beauty & Personal Care, We ensure 100% organic and quality products at a cheap rate to u.Stay with us!</p>
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>Dhaka, Bangladesh</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@fermadobd.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>01742-011181</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-dark mb-2" href="index.html"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-dark mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Products</a>
                        <a class="text-dark" href="contact"><i class="fa fa-angle-right mr-2"></i>Email us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Connects with us</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-dark mb-2" href="https://www.youtube.com/@fermadobd1598"><i class="fa fa-angle-right mr-2"></i>Youtube</a>
                        <a class="text-dark mb-2" href="https://www.instagram.com/fermadobd/?igshid=YmMyMTA2M2Y%3D"><i class="fa fa-angle-right mr-2"></i>Instagram</a>
                        <a class="text-dark mb-2" href="https://www.facebook.com/fermado.bd"><i class="fa fa-angle-right mr-2"></i>Facebook</a>
                        <a class="text-dark" href="contact"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
                    <form action="">
                        <div class="form-group">
                            <input type="text" class="form-control border-0 py-4" placeholder="Your Name"
                                required="required" />
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control border-0 py-4" placeholder="Your Email"
                                required="required" />
                        </div>
                        <div>
                            <button class="btn btn-primary btn-block border-0 py-3" type="submit">Subscribe Now</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row border-top border-light mx-xl-5 py-4">
        <div class="col-md-6 px-xl-0">

        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">

        </div>
    </div>
        <div class="copyright" >
      <p>&copy; 2023 - Fermadobd</p>
    </div>


</div>

templates/navbar.html
{% load cart_tag %}




<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <div class="col-lg-3 d-none d-lg-block">
      <a href="" class="text-decoration-none">
        <h1 class="m-0 display-5 font-weight-semi-bold"><span
            class="text-primary font-weight-bold border px-3 mr-1">F</span><a class="navbar-brand"
            href="{% url 'App_Shop:home' %}"> <b>Fermado</b> </a></h1> 
      </a>
    </div>

    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"> <span
        class="navbar-toggler-icon"></span>
    </button>

    <!-- Search bar -->
    <div class="input-group">
      <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
      <button type="button" class="btn btn-outline-primary">search</button>
    </div> 


    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'App_Order:cart' %}" class="nav-link">
            <i class="fa fa-shopping-cart">
              <span class="badge badge-light">{{ request.user | cart_total }}</span>

            </i>
          </a>
        </li>
        <li class="nav-item"></li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-tie"></i>
            {{request.user.profile.username}}</a>
          <div class="dropdown-menu" aria-labelledby="nabbarDropdown">
            <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'App_Payment:orders' %}">Orders</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item">
          <a href="{% url 'App_Login:login' %}" class="btn btn-primary">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/topbar.html
<div class="container-fluid">
    <div class="row bg-secondary py-2 px-xl-5">
        <div class="col-lg-6 d-none d-lg-block">
            <div class="d-inline-flex align-items-center">
                <a class="text-dark" href="#">FAQs</a>
                <span class="text-muted px-2">|</span>
                <a class="text-dark" href="#">Help</a>
                <span class="text-muted px-2">|</span>

                <a href="{% url 'contact' %}" class="nav-item nav-link">Contact</a>
            </div>
        </div>
        <div class="col-lg-6 text-center text-lg-right">
            <div class="d-inline-flex align-items-center">
                <a class="text-dark px-2" href="https://www.facebook.com/fermado.bd">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <!--<a class="text-dark px-2" href="{% url 'contact' %}">-->
                <!--    <i class="fab fa-twitter"></i>-->
                <!--</a>-->
                <!--<a class="text-dark px-2" href="{% url 'contact' %}">-->
                <!--    <i class="fab fa-linkedin-in"></i>-->
                <!--</a>-->
                <a class="text-dark px-2" href="https://www.instagram.com/fermadobd/?igshid=YmMyMTA2M2Y%3D">
                    <i class="fab fa-instagram"></i>
                </a>
                <a class="text-dark pl-2" href="https://www.youtube.com/@fermadobd1598">
                    <i class="fab fa-youtube"></i>
                </a>
            </div>
        </div>
    </div>

</div>